[plugin.colorizer]
# Whether to enable this plugin.
enable = true

[plugin.word-highlighter]
# Whether to enable this plugin.
enable = true
# Whether to ignore the comment line
ignore-comment-line = false
# Disable the plugin when the file matches this pattern.
ignore-files = "*.toml,*.json,*.yml,*.log,tmp"
# Specify the keyword highlights.
#
# ```toml
# # The first item is the keyword itself, the next item is the highlight group for the keyword.
# # By default only TODO is highlighted and it's linked to `Todo` highlight group.
# keyword-highlight = [ ["TODO", "Todo"] ]
#
# # You can extend this list to define more keywords and their corresponding highlight group.
# keyword-highlight = [ ["TODO", "Todo"], ["FIXME", "Error"] ]
# ```
keyword-highlight = [["TODO", "Todo"]]
# This flag controls whether to only highlight the keywords in the comment line.
#
# This flag is set as `true` by default.
keyword-highlight-comment-line-only = true

[plugin.ctags]
# Whether to enable this plugin.
enable = true
# Disable this plugin if the file size exceeds the max size limit.
#
# By default the max file size limit is 4MiB.
max-file-size = 4194304

[plugin.git]
# Whether to enable this plugin.
enable = true


[plugin.lsp]
# Whether to enable this plugin.
enable = true
# Whether to include the declaration when invoking `ClapAction lsp.reference`.
include-declaration = true
