fork = false
idle = true
maximized = false
no-multigrid = false
theme = "auto"
srgb = false
tabs = false
title-hidden = true
vsync = true
wsl = false
neovim-bin = "~/.local/share/bob/nvim-bin/nvim"

[font]
size = 14
hinting = "full"
normal = ["Maple Mono NF"]
