fork = false
idle = true
maximized = false
no-multigrid = false
theme = "auto"
srgb = false
tabs = false
title-hidden = true
vsync = true
wsl = false

[font]
size = 11
hinting = "full"
normal = ["Maple Mono NF"]
